### ISSUE TITLE
Wol Plugin authorization problem

### ISSUE THREAD

**Issue by antoinetroy39** [UB-Mannheim/glpi-wol#4]
Hey i have a problem with the plugin i have installed wol with git and im on wamp server 3.2.9 with phpmyadmin 5.2.0 and PHP 8.1.0
to be compatible with glpi but when i go to action and select wol for my computer he say wol not configure so go in plugins configuration to see but i get "i dont authorization to do this" but im in super admin i start to use glpi so im little bad but i need to use wol in glpi directly sorry for my bad english im french and thanks for help if you see this .

**Comment by dennmuel** [comment]
Hi,
could you please check, if this behavior happens only with the WoL plugin? Or does it occur ẃith other plugins as well? Does the GLPI log give you anything helpful?

To be honest, I don't have any experience with GLPI on Windows/wamp, so I can't promise any help, if the problem turns out to be related to this. Anyway, you might want to check, if the permissions on the file system are set correctly.

**Comment by antoinetroy39** [comment]
Hello and thank you for reacting so from what I could see it happens only with the plugin wol I tried to disable the other plugins but nothing. Too in logs of glpi when i try to configure the plugin i get a lot of PHP error

**Comment by antoinetroy39** [comment]
Hi i have a new question about the plugin, can you send me a exemple of the database [glpi_plugin_wakeonlan_configs] to see what is the result when it can be configured. thanks

**Comment by dennmuel** [comment]
> Hi i have a new question about the plugin, can you send me a exemple of the database [glpi_plugin_wakeonlan_configs] to see what is the result when it can be configured. thanks

That depends on how you configure it. When using remote mode it should look something like this:
|id|type|value|
|---|---|---|
|1|entities_id|0|
|2|wolmethod|remote|
|3|remoteurl|http://mywolserver.example.org/|
|4|macfield|mycustommacfield|
|5|broadfield|mycustombroadfield|
|6|custom_post|&#38;key1=value1#38;key2=value2|

The last three may be empty, of course.

If your GLPI server is the one sending the wol signal it should just say "local" for wolmethod and maybe some empty values for the rest of the config options.

**Comment by dennmuel** [comment]
> Hello and thank you for reacting so from what I could see it happens only with the plugin wol I tried to disable the other plugins but nothing. Too in logs of glpi when i try to configure the plugin i get a lot of PHP error

Other plugins should not interfere. Can you elaborate on the php errors or maybe post your log? Did you check the file permissions?

**Comment by antoinetroy39** [comment]
Hey, This is the PHP error logs when i try to configure the plugin:

```
[23-Nov-2022 14:40:52 UTC] PHP Warning:  Undefined array key "wolmethod" in C:\wamp64\www\glpi\plugins\wakeonlan\inc\wol.class.php on line 87
[23-Nov-2022 14:40:52 UTC] PHP Stack trace:
[23-Nov-2022 14:40:52 UTC] PHP   1. {main}() C:\wamp64\www\glpi\front\massiveaction.php:0
[23-Nov-2022 14:40:52 UTC] PHP   2. MassiveAction->process() C:\wamp64\www\glpi\front\massiveaction.php:59
[23-Nov-2022 14:40:52 UTC] PHP   3. MassiveAction->processForSeveralItemtypes() C:\wamp64\www\glpi\src\MassiveAction.php:1381
[23-Nov-2022 14:40:52 UTC] PHP   4. PluginWakeonlanWOL::processMassiveActionsForOneItemtype($ma = class MassiveAction { public $POST = ['_glpi_csrf_token' => '57bca7cdc327a6bb08ca9793e4f4f5cff3e58e51937234f9b4fc1b227209fbcf']; public $results = ['ok' => 0, 'noaction' => 0, 'ko' => 0, 'noright' => 0, 'messages' => [...]]; private $action = 'wake'; private $action_name = 'Wake On LAN'; private $processor = 'PluginWakeonlanWOL'; private $items = ['Computer' => [...]]; private $identifier = 2014524979; private $nb_items = 1; private $nb_done = 0; private $done = []; private $remainings = ['Computer' => [...]]; private $fields_to_remove_when_reload = [0 => 'fields_to_remove_when_reload', 1 => 'timer', 2 => 'timeout_delay']; private $timeout_delay = 117; private $timer = class Timer { public $timer = 1669214452.7171 }; private $check_item = NULL; private $redirect = 'http://172.20.74.67/glpi/front/computer.form.php?id=6'; private $display_progress_bars = FALSE; private $progress_bar_displayed = NULL; private $message_after_redirect = []; private $current_itemtype = NULL }, $item = class Computer { protected $type = -1; protected $displaylist = TRUE; public $showdebug = FALSE; public $taborientation = 'vertical'; public $get_item_to_display_tab = TRUE; public $fields = []; public $input = []; public $updates = []; public $oldvalues = []; public $dohistory = TRUE; public $history_blacklist = []; public $auto_message_on_action = TRUE; public $no_form_page = FALSE; public $additional_fields_for_dictionnary = []; protected $fkfield = ''; protected $searchopt = FALSE; protected $usenotepad = TRUE; public $deduplicate_queued_notifications = TRUE; public $right = NULL; public $devices = []; protected $last_clone_index = NULL; protected ?CommonDBTM $agent = NULL }, $ids = [6 => '6']) C:\wamp64\www\glpi\src\MassiveAction.php:1403
[23-Nov-2022 14:40:52 UTC] PHP   5. PluginWakeonlanWOL->wake($mac = '28:92:4a:c9:53:99', $broad = '172.20.74.255') C:\wamp64\www\glpi\plugins\wakeonlan\inc\wol.class.php:171
```

**Comment by antoinetroy39** [comment]
And here the wol.class.php 

```
<?php

/**
 * Copyright (C) 2021  Mannheim University Library
 * 
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License along
 * with this program. If not, see <http://www.gnu.org/licenses/>. 
 */


class PluginWakeonlanWOL extends CommonDBTM
{

   public function calc_broadcast($ip, $mask) {
      $wcmask = long2ip(~ip2long($mask));
      $subnet = long2ip(ip2long($ip) & ip2long($mask));
      $broad = long2ip(ip2long($ip) | ip2long($wcmask));
      return $broad;
   }

   public function get_netinfo($items_id, $item) {
      global $DB;
      $query = [
         'SELECT' => ['glpi_networkports.mac', 'glpi_ipaddresses.name', 'glpi_ipnetworks.netmask'],
         'FROM' => 'glpi_networkports',
         'INNER JOIN' => [
            'glpi_networknames' => [
               'ON' => [
                  'glpi_networknames' => 'items_id',
                  'glpi_networkports' => 'id',
                  ['AND' => ['glpi_networknames.itemtype' => 'NetworkPort']],
               ]
            ],
            'glpi_ipaddresses' => [
               'ON' => [
                  'glpi_ipaddresses' => 'items_id',
                  'glpi_networknames' => 'id',
                  ['AND' => ['glpi_ipaddresses.itemtype' => 'NetworkName']]
               ]
            ],
            'glpi_ipaddresses_ipnetworks' => [
               'ON' => [
                  'glpi_ipaddresses_ipnetworks' => 'ipaddresses_id',
                  'glpi_ipaddresses' => 'id'
               ]
            ],
            'glpi_ipnetworks' => [
               'ON' => [
                  'glpi_ipnetworks' => 'id',
                  'glpi_ipaddresses_ipnetworks' => 'ipnetworks_id'
               ]
            ]
         ],
         'WHERE' => [
            'glpi_networkports.items_id' => $DB->escape($items_id),
            'glpi_networkports.itemtype' => $DB->escape($item->getType()),
            'glpi_ipaddresses.version' => "4",
            // TODO: support IPv6
         ]
      ];

      $result = [];
      foreach ($DB->request($query) as $netinfo) {
         if (filter_var($netinfo['name'], FILTER_VALIDATE_IP) && filter_var($netinfo['netmask'], FILTER_VALIDATE_IP)) {
            $netinfo['broad'] = $this->calc_broadcast($netinfo['name'], $netinfo['netmask']);
         }
         if (filter_var($netinfo['mac'], FILTER_VALIDATE_MAC) && filter_var($netinfo['broad'], FILTER_VALIDATE_IP)) {
             array_push($result, $netinfo);
         }
      }
      return $result;
   }

   public function wake($mac, $broad) {
      $wolConfig = new PluginWakeonlanConfig();
      $wolConfig->getConfig();
      $wolmethod = $wolConfig->fields['wolmethod'];
      if (!$wolmethod || $wolmethod === '') {
         return [false, "No WOL method configured!"];
      }

      if ($wolmethod === 'local') {
         $hwaddr = pack('H*', preg_replace('/[^0-9a-fA-F]/', '', $mac));
         $packet = sprintf(
            '%s%s',
            str_repeat(chr(255), 6),
            str_repeat($hwaddr, 16)
         );

         $sock = socket_create(AF_INET, SOCK_DGRAM, SOL_UDP);
         if ($sock !== false) {
            $options = socket_set_option($sock, SOL_SOCKET, SO_BROADCAST, true);
            if ($options !== false) {
                $result = socket_sendto($sock, $packet, strlen($packet), 0, $broad, 7);
                socket_close($sock);
                $success = $result !== false;
            }
         }
         if ($success) {
            $response = "Sending magic packet to $broad with $mac!";
         } else {
            $response = "Unsuccessful attempt sending magic packet to $broad with $mac!";
         }
      } else if ($wolmethod === 'remote') {
         $url = $wolConfig->fields['remoteurl'];
         $macfield = $wolConfig->fields['macfield'];
         $broadfield = $wolConfig->fields['broadfield'];
         if (!filter_var($url, FILTER_VALIDATE_URL)) {
            return [false, "Remote URL invalid!"];
         }
         if (!$macfield || $macfield === '') {
            $macfield = 'mac';
         }
         if (!$broadfield || $broadfield === '') {
            $broadfield = 'broad';
         }
         $ch = curl_init($url);
         curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
         curl_setopt($ch, CURLOPT_POST, 1);
         $poststr = "$macfield=$mac&$broadfield=$broad";
         $custom_post = htmlspecialchars_decode($wolConfig->fields['custom_post']);
         if ($custom_post) {
            $poststr .= $custom_post;
         }
         curl_setopt($ch, CURLOPT_POSTFIELDS, $poststr);
         $response = curl_exec($ch);
         $curlinfo = curl_getinfo($ch);
         curl_close($ch);
         $httpcode = $curlinfo['http_code'];
         if ($httpcode != "200") {
            $success = false;
            $response = "Remote server returned HTTP code $httpcode";
         } else {
            $arr = json_decode($response, true);
            $success = $arr['success'];
            $response = htmlentities($arr['msg'], ENT_QUOTES);
         }
      }
      return [$success, $response];
   }

   static function showMassiveActionsSubForm($ma) {
      if ($ma->getAction() === 'wake') {
          echo Html::submit('Send WOL Signal', ['name' => 'massiveaction']);
          return true;
      }
      return parent::showMassiveActionsSubForm($ma);
   }

   static function processMassiveActionsForOneItemtype($ma, $item, $ids) {
      if ($ma->getAction() === 'wake') {
         $wol = new self();
         foreach ($ids as $id) {
            $netinfos = $wol->get_netinfo($id, $item);
            if (count($netinfos) < 1) {
               $ma->itemDone($item->getType(), $id, MassiveAction::ACTION_KO);
               $ma->addMessage("Could not retrieve suitable netinfo for item ID $id.");
               return;
            }
            foreach ($netinfos as $ni) {
               list($success, $response) = $wol->wake($ni['mac'], $ni['broad']);
               if ($success) {
                  $ma->itemDone($item->getType(), $id, MassiveAction::ACTION_OK);
               } else {
                  $ma->itemDone($item->getType(), $id, MassiveAction::ACTION_KO);
                  $ma->addMessage($response);
               }
            }
         }
         return;
      } else {
         parent::processMassiveActionsForOneItemtype($ma, $item, $ids);
      }
   }

}

```

**Comment by migdav-dsn** [comment]
Hi, 
same problem on a Debian 10  (apache, php8.2 ). The message obtained when you want to configure it : "Vous n'avez pas les droits requis pour réaliser cette action."

In the access-errors.log : 
User ID: 683 tried to access or perform an action on /glpi/plugins/wakeonlan/front/config.php with insufficient rights. Additional information: User failed a can* method check for right 4 (CREATE) on item Type$
        Stack Trace:
                /var/www/glpi/src/CommonDBTM.php:3001 displayRightError()
                /var/www/glpi/src/CommonDBTM.php:2738 check()
                /var/www/glpi/plugins/wakeonlan/inc/config.class.php:54 initForm()
                /var/www/glpi/plugins/wakeonlan/front/config.php:39 showForm()

The owner of the plugin folder "wakeonlan" is "www-data:www-data" and I put everything in 777 to be sure that it was not a file rights problem.

Thanks in advance

**Comment by dennmuel** [comment]
Hi @antoinetroy39,

I formatted your replies for better readability.

> Hey, This is the PHP error logs when i try to configure the plugin:
> 
> ```
> [23-Nov-2022 14:40:52 UTC] PHP Warning:  Undefined array key "wolmethod" in C:\wamp64\www\glpi\plugins\wakeonlan\inc\wol.class.php on line 87
> [23-Nov-2022 14:40:52 UTC] PHP Stack trace:
> [23-Nov-2022 14:40:52 UTC] PHP   1. {main}() C:\wamp64\www\glpi\front\massiveaction.php:0
> [23-Nov-2022 14:40:52 UTC] PHP   2. MassiveAction->process() C:\wamp64\www\glpi\front\massiveaction.php:59
> [23-Nov-2022 14:40:52 UTC] PHP   3. MassiveAction->processForSeveralItemtypes() C:\wamp64\www\glpi\src\MassiveAction.php:1381
> [23-Nov-2022 14:40:52 UTC] PHP   4. PluginWakeonlanWOL::processMassiveActionsForOneItemtype($ma = class MassiveAction { public $POST = ['_glpi_csrf_token' => '57bca7cdc327a6bb08ca9793e4f4f5cff3e58e51937234f9b4fc1b227209fbcf']; public $results = ['ok' => 0, 'noaction' => 0, 'ko' => 0, 'noright' => 0, 'messages' => [...]]; private $action = 'wake'; private $action_name = 'Wake On LAN'; private $processor = 'PluginWakeonlanWOL'; private $items = ['Computer' => [...]]; private $identifier = 2014524979; private $nb_items = 1; private $nb_done = 0; private $done = []; private $remainings = ['Computer' => [...]]; private $fields_to_remove_when_reload = [0 => 'fields_to_remove_when_reload', 1 => 'timer', 2 => 'timeout_delay']; private $timeout_delay = 117; private $timer = class Timer { public $timer = 1669214452.7171 }; private $check_item = NULL; private $redirect = 'http://172.20.74.67/glpi/front/computer.form.php?id=6'; private $display_progress_bars = FALSE; private $progress_bar_displayed = NULL; private $message_after_redirect = []; private $current_itemtype = NULL }, $item = class Computer { protected $type = -1; protected $displaylist = TRUE; public $showdebug = FALSE; public $taborientation = 'vertical'; public $get_item_to_display_tab = TRUE; public $fields = []; public $input = []; public $updates = []; public $oldvalues = []; public $dohistory = TRUE; public $history_blacklist = []; public $auto_message_on_action = TRUE; public $no_form_page = FALSE; public $additional_fields_for_dictionnary = []; protected $fkfield = ''; protected $searchopt = FALSE; protected $usenotepad = TRUE; public $deduplicate_queued_notifications = TRUE; public $right = NULL; public $devices = []; protected $last_clone_index = NULL; protected ?CommonDBTM $agent = NULL }, $ids = [6 => '6']) C:\wamp64\www\glpi\src\MassiveAction.php:1403
> [23-Nov-2022 14:40:52 UTC] PHP   5. PluginWakeonlanWOL->wake($mac = '28:92:4a:c9:53:99', $broad = '172.20.74.255') C:\wamp64\www\glpi\plugins\wakeonlan\inc\wol.class.php:171
> ```

This message does not seem to originate from the plugin _configuration_. I think this is from trying to _use_ the plugin in a "massive action", i.e. trying to wake multiple machines. (This fails, of course, because you haven't actually configured the plugin yet.)

> And here the wol.class.php

Again, this file is not used for configuration; this is used to actually perform the action. The file relevant for the configuration page is `config.class.php`.

I have the feeling there is a misunderstanding and you might have never actually opened the configuration page. Can you please, as the GLPI admin, go to "Setup -> Plugins" and open the plugin configuration?
![image](https://user-images.githubusercontent.com/21078769/203776713-1eec76e0-1526-4886-951b-68e7b9bfd4c2.png) --> ![image](https://user-images.githubusercontent.com/21078769/203776750-8d8adc9a-64e3-4572-bcb4-c1ea1882ad09.png)

It should look something like this:
![image](https://user-images.githubusercontent.com/21078769/203776833-9e9a4179-23a2-4b67-82a7-6fd68f53f19a.png)
If not, please provide a screenshot of what you actually see and what the log says to that.

**Comment by dennmuel** [comment]
Hi @migdav-dsn and thanks for your input.

> Hi, same problem on a Debian 10 (apache, php8.2 ). The message obtained when you want to configure it : "Vous n'avez pas les droits requis pour réaliser cette action."

Just for the record: We haven't tested this on php 8.2, so no guarantees given that it should work.

> In the access-errors.log : User ID: 683 tried to access or perform an action on /glpi/plugins/wakeonlan/front/config.php with insufficient rights. Additional information: User failed a can* method check for right 4 (CREATE) on item Type$ Stack Trace: /var/www/glpi/src/CommonDBTM.php:3001 displayRightError() /var/www/glpi/src/CommonDBTM.php:2738 check() /var/www/glpi/plugins/wakeonlan/inc/config.class.php:54 initForm() /var/www/glpi/plugins/wakeonlan/front/config.php:39 showForm()

I hope you don't mind me asking, but does that user 683 actually have sufficient rights, i.e. is Super-Admin? Could you cross check that please? Thanks!

I'm not ruling out, that there might actually a permission issue, but I haven't yet succeeded in trying to reproduce this behavior.

**Comment by antoinetroy39** [comment]
``@dennmuel Thanks I see what it is supposed to give but the problem is simply the fact that I can not access it when I click on the configure button and it shows me this: 

![Capture d’écran (1)](https://user-images.githubusercontent.com/118546463/203781996-8df46e9a-355d-49d9-9015-a975620f0580.png)
![Capture d’écran (2)](https://user-images.githubusercontent.com/118546463/203782001-aa52f90d-6299-4c79-8048-a11f654a00d0.png)

**Comment by antoinetroy39** [comment]
Sorry for readability  i dont know how i can formatted code : here config.class

```
class PluginWakeonlanConfig extends CommonDBTM
{
   static $rightname = "config";

   function updateValue($name, $value) {
      // retrieve current config
      $config = current($this->find(['type' => $name]));
      // set in db
      if (isset($config['id'])) {
         $result = $this->update(['id'=> $config['id'], 'value'=>$value]);
      } else {
         $result = $this->add(['type' => $name, 'value' => $value]);
      }

      // set cache
      if ($result) {
         $this->fields[$name] = $value;
      }

      return $result;
   }

   function getConfig() {
      global $DB;
      $rows = $DB->request('glpi_plugin_wakeonlan_configs');
      if (count($rows) > 0) {
         foreach ($rows as $row) {
            $this->fields[$row['type']] = $row['value'];
         }
      }
   }

   function showForm($ID, array $options = []) {
      $this->initForm($ID, $options);
      $this->showFormHeader($options);

      echo "<tr>";
      echo "<td>".__('Method', 'wakeonlan')."</td>";
      echo "<td>";
      foreach (['local', 'remote'] as $m) {
         $checked = (array_key_exists('wolmethod', $this->fields) && $this->fields['wolmethod'] === $m) ? "checked" : "";
         echo "<input type='radio' id='$m' value='$m' name='wolmethod' $checked>";
         echo "<label for='local'>" . __($m, 'wakeonalan') . "</label>";
         echo "<br/>";
      }
      echo "</td>";
      echo "</tr>";

      echo "<tr><td colspan='2'>When using remote</td></tr>";

      echo "<tr>";
      echo "<td>".__('Remote URL', 'wakeonlan')."</td>";
      echo "<td>";
      echo HTML::input('remoteurl', ['value' => array_key_exists('remoteurl', $this->fields) ? $this->fields['remoteurl'] : ""]);
      echo "</td>";
      echo "</tr>";

      echo "<tr>";
      echo "<td>".__('MAC Field', 'wakeonlan')."</td>";
      echo "<td>";
      echo HTML::input('macfield', ['value' => array_key_exists('macfield', $this->fields) ? $this->fields['macfield'] : ""]);
      echo "</td>";
      echo "</tr>";

      echo "<tr>";
      echo "<td>".__('Broadcast Field', 'wakeonlan')."</td>";
      echo "<td>";
      echo HTML::input('broadfield', ['value' => array_key_exists('broadfield', $this->fields) ? $this->fields['broadfield'] : ""]);
      echo "</td>";
      echo "</tr>";

      echo "<tr>";
      echo "<td>".__('Custom Post String', 'wakeonlan')."</td>";
      echo "<td>";
      echo HTML::input('custom_post', ['value' => array_key_exists('custom_post', $this->fields) ? $this->fields['custom_post'] : ""]);
      echo "</td>";
      echo "</tr>";

      echo "<tr class='tab_bg_2'>";
      echo "<td class='center' colspan='2'>";
      echo Html::submit(_x('button', 'Save'), ['name' => 'update']);
      echo "</td>";
      echo "</tr>\n";
      echo "</table></div>";
      Html::closeForm();

      // $this->showFormButtons($options);
      return true;
   }
}

```

**Comment by migdav-dsn** [comment]
> I hope you don't mind me asking, but does that user 683 actually have sufficient rights, i.e. is Super-Admin? Could you cross check that please? Thanks!

It's the user "admin" (superadmin on GLPI) : 
![image](https://user-images.githubusercontent.com/118549336/203789066-8b04d474-8fe9-4916-b503-8978fd019690.png)

![image](https://user-images.githubusercontent.com/118549336/203789443-2d4925c9-062e-4ae5-9636-fa846d66817e.png)

I don't have the problem to configure the others plugins, only this one : 
![image](https://user-images.githubusercontent.com/118549336/203790377-d07c8d70-3e7c-425d-8e82-6a80a5aa8cc4.png)

**Comment by dennmuel** [comment]
Thank you both for your replies and sorry for all my questions. I just needed to get some vague/contradictory information straight.

I'll try to reproduce this as soon as work allows and update this issue. Thank you very much for reporting!

---

> Sorry for readability i dont know how i can formatted code

@antoinetroy39 there is plenty of [information on markdown syntax here](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#quoting-code). When writing a comment, you'll also find the most important formatting options in the upper right corner of your comment textbox. Hope this helps. :)

**Comment by dennmuel** [comment]
Oh, one more question: You are both using GLPI 10.0.5 and wakeonlan 0.0.3, correct?

**Comment by migdav-dsn** [comment]
> Oh, one more question: You are both using GLPI 10.0.5 and wakeonlan 0.0.3, correct?

Yes, GLPI 10.0.5 and wakeonlan 0.0.3

**Comment by dennmuel** [comment]
Hi,
could you please give me the output of this query?

`select a.name as rightname, a.rights, b.name as profilename from glpi_profilerights a join glpi_profiles b on a.profiles_id = b.id where b.name = "Super-Admin" and a.name = "config";`

EDIT:
I just cannot reproduce this. It seems that in your instances, [this line](https://github.com/glpi-project/glpi/blob/eb12e6387107f2c7b34a2458a052aa9f04226a31/src/CommonDBTM.php#L2995) must return something other than "true", so maybe one of you could copy [this function](https://github.com/glpi-project/glpi/blob/10.0.5/src/CommonDBTM.php#L2850-L2970) to config.class.php and add some `error_log` statements or something so we can see on which line it returns.

**Comment by migdav-dsn** [comment]
> Hi, could you please give me the output of this query?
> 
> `select a.name as rightname, a.rights, b.name as profilename from glpi_profilerights a join glpi_profiles b on a.profiles_id = b.id where b.name = "Super-Admin" and a.name = "config";`

Hi,

the result is : 
![image](https://user-images.githubusercontent.com/118549336/203991114-d386cf3b-7a65-44ae-a042-65d66af2fa4c.png)

**Comment by dennmuel** [comment]
Hi, thanks for your quick reply. This might explain the issue. According to the [documentation](https://glpi-developer-documentation.readthedocs.io/en/master/devapi/acl.html?highlight=rightname#rights-definition) this means that the profile in question does only have READ and UPDATE permissions, but not CREATE (which would be 4 or higher).

You could update the the rights accordingly or use a profile that already has the permissions. You can check for profile with sufficient rights by running the following and see if one of the entries has a "rights" value of 4 or higher:
`select a.*, b.name from glpi_profilerights a join glpi_profiles b on a.profiles_id = b.id  where a.name = "config";`

**Comment by dennmuel** [comment]
I added a commit 8695284418b036211c4a85ce5cd10da8c36e4659 to the dev branch which adds default configuration on installation. Perhaps that could solve this problem, since you would theoretically not need the CREATE permission anymore when you open the config page. (As a convenient side effect you wouldn't even need to access the page if you use 'local' mode anyway.)

Can you please uninstall the plugin, install the current state of the dev branch and let me know, if this helps?

**Comment by migdav-dsn** [comment]
> Hi, thanks for your quick reply. This might explain the issue. According to the [documentation](https://glpi-developer-documentation.readthedocs.io/en/master/devapi/acl.html?highlight=rightname#rights-definition) this means that the profile in question does only have READ and UPDATE permissions, but not CREATE (which would be 4 or higher).
> 
> You could update the the rights accordingly or use a profile that already has the permissions. You can check for profile with sufficient rights by running the following and see if one of the entries has a "rights" value of 4 or higher: `select a.*, b.name from glpi_profilerights a join glpi_profiles b on a.profiles_id = b.id where a.name = "config";`

Sorry, the account name is "admin", not "super-admin".
![image](https://user-images.githubusercontent.com/118549336/204016400-2cd1539d-83f5-45ae-913b-9c0935841ce8.png)

The rights are greater than 4 for the admin account: 31

**Comment by migdav-dsn** [comment]
It's ok, after modifying the rights to 31 (3 before modification) for the super-admin profile (as for the admin user).
![image](https://user-images.githubusercontent.com/118549336/204021222-72a54f6c-1832-4fda-a932-41ef56be0119.png)

I would go back on the modifications after setting up the plugin.
Thanks a lot.
